load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Load the rules' repo
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "685052b498b6ddfe562ca7a97736741d87916fe536623afb7da2824c0211c369",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
    ],
)

# From that repo, load these macros
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

# Dependencies for the toolchain and the rules' code itself
go_rules_dependencies()

# Install a Golang toolchain into the sandbox
go_register_toolchains(version = "1.18.3")
